BASIC:
  PROTOCOL_VERSION: 2
  BAUDRATE: 1000000 # 1M bps

HAND:
  NAME: 'GX10'
  NUM: 10
  THUMB_IDS: [1, 2, 3, 4]
  INDEX_IDS: [5, 6, 7]
  MID_IDS: [8, 9, 10]


ExtendedPos:
  Motor1: 
    Pos_kp: 300
    Pos_kd: 100
    Pos_ki: 10
    Profile_vel: 800 # unit 0.229 rev/min
    Profile_acc: 200 # unit 214.58 rev/min2
 


